
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/gitops-demo-node-app/
patches:
  - path: deployment.yaml
    target:
      name: myapp
      kind: Deployment