
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
# bases:
#   - ../../../base/nginx/
# resources:
#   - deployment.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/nginx/
patches:
  - path: deployment.yaml
    target:
      name: nginx
      kind: Deployment