apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-demo-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: gitops-demo-node-app-container
        image: vipulshukla71098/gitops-demo-node-app:14
        ports:
        - containerPort: 5000
